const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Amoon Bloom API',
      version: '1.0.0',
      description:
        'Mobile ecommerce API for **Amoon Bloom**. Use **Authorize** with your JWT. Base URL: **/api/v1** (or **/api**). Customers can register **FCM tokens** and **notification preferences** under **Push notifications**. Managers get **managerPermissions** after sign-in.',
    },
    // Relative URL: Swagger “Try it out” uses the same host as the page (localhost, LAN IP, or production).
    servers: [
      { url: '/api/v1', description: 'API v1 (all routes)' },
    ],
    tags: [
      { name: 'Auth', description: 'Signup, login, Google OAuth, password reset, get/update user by ID' },
      {
        name: 'User Profile',
        description: 'Current user profile by token: profile, preferred language, address',
      },
      {
        name: 'Push notifications',
        description:
          '**Amoon Bloom** mobile push (Firebase Cloud Messaging). Register **POST /user/push/token** after login; **GET/PATCH /user/notifications/preferences** for toggles (defaults all on). Server sends order lifecycle pushes when Firebase credentials are configured.',
      },
      {
        name: 'Users',
        description: [
          '### User management (admin)',
          '',
          'Create and maintain **customer** and **manager** accounts. Requires an **Administrator** JWT, or a **Manager** JWT holding the **USERS** permission (for customer accounts) and/or the **MANAGERS** permission (for manager accounts — including creating new managers and assigning their permissions). Regardless of permissions, a manager can never see, create, modify, or delete an **ADMIN** account, or set any account\'s role to ADMIN — those rows return **404** to a manager and any attempt to assign the ADMIN role returns **403**. Roles the caller isn\'t permitted to see are also excluded from **GET /users** and **GET /users/stats**.',
          '',
          '### Account types',
          '',
          '- **Customer** — Default shopper account. Use when role is omitted or set to CUSTOMER.',
          '- **Manager** — Staff with restricted API access. Needs a **job title** and a **non-empty permission list**. Managers use the same sign-in flow; the response includes **managerPermissions** for your front-end. The API always enforces permissions server-side.',
          '',
          '### Adding a manager (recommended flow)',
          '',
          '1. **GET /users/manager-permissions** — Load the catalog (labels + help text) for checkboxes or toggles.',
          '2. Let the admin pick one or more areas (e.g. orders and products).',
          '3. **POST /users** — Send role MANAGER, managerTitle, managerPermissions, and optionally an avatar image URL from the upload endpoint.',
          '4. After the manager signs in, use **managerPermissions** to show or hide sections in your admin app.',
          '',
          '### Permission keys (JSON strings, uppercase)',
          '',
          'PRODUCTS · ORDERS · CATEGORIES · SECTIONS · BANNERS · CONTACT · SETTINGS · PROMO_CODES · ANALYTICS · REGIONS · REVIEWS · DELIVERY_ZONES · VAT · CASH_ARRANGEMENT · NOTIFICATIONS · USERS · MANAGERS',
          '',
          'You can assign several at once (for example orders **and** products).',
          '',
          '### Important',
          '',
          'Administrator accounts **cannot** be created through **POST /users**. Provision the first admin via your seed script or database.',
        ].join('\n'),
      },
      { name: 'Upload', description: 'Image upload (Bunny CDN)' },
      { name: 'Categories', description: 'Product categories (admin CRUD, public list)' },
      {
        name: 'Products',
        description:
          'Products (admin CRUD, public list/detail). On create or update, set **categoryId** to the UUID from **GET /categories** to place the product in that category.',
      },
      {
        name: 'Cart',
        description:
          'User cart (add, update, remove, get). **GET /cart/suggestions** returns category-aware picks when the cart has items; if the cart is empty, it returns a **random** sample of in-stock products (same size limits via query params).',
      },
      {
        name: 'Orders',
        description:
          'Checkout and order management. **GET /orders/history** lists the signed-in customer\'s orders; **GET /orders/admin/history** is the staff audit log (optional **includeItems**). **GET /orders/{id}/status** is a lightweight status poll after checkout. Successful checkout triggers an **order placed** push when FCM is configured and **orderStatus** notifications are on. Admin status updates send matching pushes.',
      },
      { name: 'Banners', description: 'Landing page banners (public list; admin add, reorder, delete)' },
      { name: 'Sections', description: 'Admin-created sections for user panel (e.g. Ramadan Deals) with products and categories' },
      {
        name: 'Admin analytics',
        description:
          'Dashboard metrics. **GET /admin/analytics/revenue** — time series + summary. **GET /admin/analytics/kpi** — totals & per-status. **GET /admin/analytics/revenue/by-category** — ranked categories. **GET /admin/analytics/sales/by-day** — each UTC day\'s net order count & revenue (zeros filled). Presets include **all_time** (monthly on long horizons). **Admin** or manager with **ORDERS** or **SETTINGS**. **UTC**.',
      },
      {
        name: 'Promo codes',
        description:
          'Discount / promo codes. **Admin**: full CRUD at `/promo-codes` (requires ADMIN or MANAGER with `PROMO_CODES`). Scope via `appliesTo` (ALL_PRODUCTS / SPECIFIC_PRODUCTS / SPECIFIC_CATEGORIES). Type is PERCENTAGE (with optional `maxDiscountAmount` cap) or FIXED. Availability via `startsAt`/`expiresAt`; `minOrderAmount` / `maxOrderAmount` guard cart totals; `usageLimit` / `usageLimitPerUser` cap redemptions. **User**: `GET /promo-codes/available` for active offers, `POST /promo-codes/validate` to preview the discount on the user\'s cart before checkout.',
      },
      { name: 'Addresses', description: 'Saved shipping addresses for the authenticated user. Up to 10 per account. One address is always the default.' },
      {
        name: 'Contact',
        description:
          'In-app contact / issue submission. **POST /contact/issue** — authenticated; body is just `subject` + `message`. `userId` is taken from the JWT. The user must have a phone number on their profile — if not, returns 400 and the app should send `PATCH /user/profile/phone` first.',
      },
      {
        name: 'Contact Admin',
        description:
          'Admin / manager view of user-submitted contacts. Requires **ADMIN** or **MANAGER** with the **CONTACT** permission. **GET /contact/admin/issues** lists submissions with the sender\'s user details (name, email, phone) embedded.',
      },
      {
        name: 'Reviews',
        description:
          'Public product star-rating + written reviews. **GET /reviews/product/:productId** — paginated list plus `avgRating`/`reviewCount`. **POST /reviews/product/:productId** — signed-in (JWT optional) or guest; guests need `guestName` + `guestEmail` and are only accepted while the admin-controlled **allowGuestReviews** setting is on.',
      },
      {
        name: 'Reviews Admin',
        description:
          'Admin / manager moderation of customer reviews. Requires **ADMIN** or **MANAGER** with the **REVIEWS** permission. **GET /reviews/admin** lists every review across all products; **DELETE /reviews/admin/:id** removes any of them.',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      parameters: {
        XRegionHeader: {
          in: 'header',
          name: 'X-Region',
          required: false,
          schema: { type: 'string', example: 'UAE' },
          description:
            'Storefront region code (e.g. `UAE`, `SA`) — see **GET /regions** for valid codes. Controls which region the catalog is filtered to. Defaults to the default region when omitted or unknown. Ignored for staff (admin/manager) reads, which see all regions.',
        },
        RegionFilterQuery: {
          in: 'query',
          name: 'region',
          required: false,
          schema: { type: 'string', example: 'SA' },
          description:
            'Admin-only filter: narrow results to a single region **code**. Storefront requests should use the `X-Region` header instead.',
        },
        StatusFilterQuery: {
          in: 'query',
          name: 'status',
          required: false,
          schema: { type: 'string', enum: ['DRAFT', 'PUBLISHED'] },
          description: 'Admin-only filter by publish state. Storefront requests always see PUBLISHED only.',
        },
      },
      schemas: {
        PublishStatus: {
          type: 'string',
          enum: ['DRAFT', 'PUBLISHED'],
          description:
            'Publish state for region-aware content. New items default to **DRAFT** (hidden from the storefront). Only **PUBLISHED** items are returned to non-staff requests.',
        },
        Region: {
          type: 'object',
          description: 'A storefront region. Regions are data (not an enum) — new ones can be added at runtime via POST /regions with no migration.',
          properties: {
            id: { type: 'string', format: 'uuid' },
            code: { type: 'string', example: 'UAE', description: 'Short code sent in the X-Region header' },
            name: { type: 'string', example: 'United Arab Emirates' },
            name_ar: { type: 'string', nullable: true, example: 'الإمارات العربية المتحدة' },
            legalEntity: { type: 'string', nullable: true, example: 'AMOON BLOOM Trading L.L.C S.O.C™', description: 'Legal entity name shown in the storefront footer copyright line for this region. Null falls back to the frontend default.' },
            shippingFlatRate: { type: 'number', nullable: true, example: 25, description: 'Flat shipping fee charged on every order placed in this region. Null = no fee configured (ships free).' },
            iso2: { type: 'string', nullable: true, example: 'AE', description: 'ISO 3166-1 alpha-2 code — renders this region\'s flag in the storefront picker. Null shows a placeholder.' },
            urlSlug: { type: 'string', nullable: true, example: 'ae', description: 'Lowercase URL segment for the storefront\'s permanent per-region public routes (e.g. /ae/en/). Web-only — NOT used for API scoping (clients still send `code` via X-Region). Null = no dedicated route.' },
            contactEmail: { type: 'string', nullable: true, example: 'support@amoonbloom.com', description: 'Support email shown across the storefront for this region. Null falls back to the frontend default.' },
            contactPhone: { type: 'string', nullable: true, example: '+971 50 606 7910', description: 'Support phone number for this region. Null falls back to the frontend default.' },
            whatsappNumber: { type: 'string', nullable: true, example: '+971 50 606 7910', description: 'WhatsApp contact number for this region (wa.me link is derived from the digits). Null falls back to the frontend default.' },
            address: { type: 'string', nullable: true, example: 'Dubai, United Arab Emirates', description: 'Business address shown for this region. Null falls back to the frontend default.' },
            address_ar: { type: 'string', nullable: true, example: 'دبي، الإمارات العربية المتحدة', description: 'Arabic address. Null falls back to `address`.' },
            hours: { type: 'string', nullable: true, example: 'Daily · 10:00 — 00:00 (Dubai time)', description: 'Business hours shown for this region. Null falls back to the frontend default.' },
            hours_ar: { type: 'string', nullable: true, description: 'Arabic business hours. Null falls back to `hours`.' },
            registrationCity: { type: 'string', nullable: true, example: 'Dubai', description: 'Legal citation field (see registrationCity_ar note below) — required to create a region, nullable only for regions that predate this field.' },
            registrationCity_ar: { type: 'string', nullable: true, example: 'دبي' },
            currencyDisplayName: { type: 'string', nullable: true, example: 'UAE Dirhams (AED)' },
            currencyDisplayName_ar: { type: 'string', nullable: true, example: 'الدرهم الإماراتي' },
            vatLawName: { type: 'string', nullable: true, example: 'UAE Federal Decree-Law on Value Added Tax' },
            vatLawName_ar: { type: 'string', nullable: true, example: 'المرسوم بقانون اتحادي بشأن ضريبة القيمة المضافة' },
            dataProtectionLawName: { type: 'string', nullable: true, example: 'UAE Federal Decree-Law No. 45 of 2021 on the Protection of Personal Data (PDPL)' },
            dataProtectionLawName_ar: { type: 'string', nullable: true },
            dataProtectionAuthority: { type: 'string', nullable: true, example: 'UAE Data Office' },
            dataProtectionAuthority_ar: { type: 'string', nullable: true, example: 'مكتب البيانات الإماراتي' },
            ipLawName: { type: 'string', nullable: true, example: 'UAE Federal Law No. 38 of 2021 on Intellectual Property Rights' },
            ipLawName_ar: { type: 'string', nullable: true },
            consumerProtectionLawName: { type: 'string', nullable: true, example: 'UAE Federal Law No. 15 of 2020 on Consumer Protection' },
            consumerProtectionLawName_ar: { type: 'string', nullable: true },
            consumerProtectionAuthority: { type: 'string', nullable: true, example: 'UAE Ministry of Economy Consumer Protection Department' },
            consumerProtectionAuthority_ar: { type: 'string', nullable: true },
            standardsAuthority: { type: 'string', nullable: true, example: 'Emirates Authority for Standardisation and Metrology (ESMA)' },
            standardsAuthority_ar: { type: 'string', nullable: true },
            isDefault: { type: 'boolean', description: 'The region used when the client sends no/unknown X-Region. Exactly one region is default.' },
            isActive: { type: 'boolean', description: 'Inactive regions are hidden from the public GET /regions list and cannot be selected.' },
            sortOrder: { type: 'integer', example: 0 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        RegionRef: {
          type: 'object',
          description: 'Compact region reference embedded in region-aware entities.',
          properties: {
            id: { type: 'string', format: 'uuid' },
            code: { type: 'string', example: 'UAE' },
            name: { type: 'string', example: 'United Arab Emirates' },
            name_ar: { type: 'string', nullable: true, example: 'الإمارات العربية المتحدة' },
          },
        },
        RegionCreate: {
          type: 'object',
          description: 'The 18 legal-citation fields (registrationCity(_ar) through standardsAuthority(_ar)) are REQUIRED — a region cannot be created without accurate legal citations for its own jurisdiction. See the Region schema for each field\'s meaning.',
          required: [
            'code', 'name',
            'registrationCity', 'registrationCity_ar',
            'currencyDisplayName', 'currencyDisplayName_ar',
            'vatLawName', 'vatLawName_ar',
            'dataProtectionLawName', 'dataProtectionLawName_ar',
            'dataProtectionAuthority', 'dataProtectionAuthority_ar',
            'ipLawName', 'ipLawName_ar',
            'consumerProtectionLawName', 'consumerProtectionLawName_ar',
            'consumerProtectionAuthority', 'consumerProtectionAuthority_ar',
            'standardsAuthority', 'standardsAuthority_ar',
          ],
          properties: {
            code: { type: 'string', example: 'KW', description: 'Unique short code (uppercased). Sent by clients in X-Region.' },
            name: { type: 'string', example: 'Kuwait' },
            name_ar: { type: 'string', nullable: true, example: 'الكويت' },
            legalEntity: { type: 'string', nullable: true, example: 'AMOON BLOOM Trading L.L.C S.O.C™', description: 'Legal entity name for the footer copyright line in this region. Omit/null to use the frontend default.' },
            shippingFlatRate: { type: 'number', nullable: true, example: 25, description: 'Flat shipping fee for orders in this region. Omit/null for free shipping.' },
            iso2: { type: 'string', nullable: true, example: 'KW', description: '2-letter ISO country code for the flag shown in the picker. Omit/null to show a placeholder.' },
            urlSlug: { type: 'string', nullable: true, example: 'kw', description: 'Lowercase URL segment for this region\'s public routes (e.g. /kw/en/). Web-only, not used for API scoping. Omit/null for no dedicated route.' },
            contactEmail: { type: 'string', nullable: true, example: 'support@amoonbloom.com', description: 'Support email for this region. Omit/null to use the frontend default.' },
            contactPhone: { type: 'string', nullable: true, example: '+971 50 606 7910', description: 'Support phone for this region. Omit/null to use the frontend default.' },
            whatsappNumber: { type: 'string', nullable: true, example: '+971 50 606 7910', description: 'WhatsApp number for this region. Omit/null to use the frontend default.' },
            address: { type: 'string', nullable: true, example: 'Dubai, United Arab Emirates', description: 'Business address for this region. Omit/null to use the frontend default.' },
            address_ar: { type: 'string', nullable: true, description: 'Arabic address. Omit/null to fall back to `address`.' },
            hours: { type: 'string', nullable: true, example: 'Daily · 10:00 — 00:00 (Dubai time)', description: 'Business hours for this region. Omit/null to use the frontend default.' },
            hours_ar: { type: 'string', nullable: true, description: 'Arabic business hours. Omit/null to fall back to `hours`.' },
            registrationCity: { type: 'string', example: 'Rabat', description: 'Required. City shown in "registered and operating in {city}, {country}" and the dispute-jurisdiction clause.' },
            registrationCity_ar: { type: 'string', example: 'الرباط', description: 'Required.' },
            currencyDisplayName: { type: 'string', example: 'Moroccan Dirhams (MAD)', description: 'Required. Full currency name shown in the pricing sentence.' },
            currencyDisplayName_ar: { type: 'string', example: 'الدرهم المغربي', description: 'Required.' },
            vatLawName: { type: 'string', example: 'Moroccan VAT law (Code Général des Impôts)', description: 'Required.' },
            vatLawName_ar: { type: 'string', description: 'Required.' },
            dataProtectionLawName: { type: 'string', example: "Morocco's Law No. 09-08 on the Protection of Individuals with regard to the Processing of Personal Data", description: 'Required.' },
            dataProtectionLawName_ar: { type: 'string', description: 'Required.' },
            dataProtectionAuthority: { type: 'string', example: 'CNDP (Commission Nationale de contrôle de la protection des Données à caractère Personnel)', description: 'Required.' },
            dataProtectionAuthority_ar: { type: 'string', description: 'Required.' },
            ipLawName: { type: 'string', example: 'Moroccan Law No. 17-97 on the Protection of Industrial Property', description: 'Required.' },
            ipLawName_ar: { type: 'string', description: 'Required.' },
            consumerProtectionLawName: { type: 'string', example: "Morocco's Law No. 31-08 on Consumer Protection", description: 'Required.' },
            consumerProtectionLawName_ar: { type: 'string', description: 'Required.' },
            consumerProtectionAuthority: { type: 'string', example: 'Moroccan Ministry of Industry and Trade', description: 'Required.' },
            consumerProtectionAuthority_ar: { type: 'string', description: 'Required.' },
            standardsAuthority: { type: 'string', example: 'IMANOR (Institut Marocain de Normalisation)', description: 'Required.' },
            standardsAuthority_ar: { type: 'string', description: 'Required.' },
            isDefault: { type: 'boolean', example: false, description: 'Set true to make this the default region (unsets any other default).' },
            isActive: { type: 'boolean', example: true },
            sortOrder: { type: 'integer', example: 2 },
          },
        },
        DeliveryZone: {
          type: 'object',
          description: 'Admin-managed delivery sub-area within a region (e.g. UAE\'s emirates). Scoped per-region, not global.',
          properties: {
            id: { type: 'string', format: 'uuid' },
            regionId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Dubai' },
            name_ar: { type: 'string', nullable: true, example: 'دبي' },
            isActive: { type: 'boolean' },
            sortOrder: { type: 'integer', example: 1 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        DeliveryZoneCreate: {
          type: 'object',
          required: ['regionId', 'name'],
          properties: {
            regionId: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Dubai' },
            name_ar: { type: 'string', nullable: true, example: 'دبي' },
            isActive: { type: 'boolean', example: true },
            sortOrder: { type: 'integer', example: 1 },
          },
        },
        ManagerPermissionKey: {
          type: 'string',
          enum: ['PRODUCTS', 'ORDERS', 'CATEGORIES', 'SECTIONS', 'BANNERS', 'CONTACT', 'SETTINGS', 'PROMO_CODES', 'ANALYTICS', 'REGIONS', 'REVIEWS', 'DELIVERY_ZONES', 'VAT', 'CASH_ARRANGEMENT', 'NOTIFICATIONS', 'USERS', 'MANAGERS'],
          description:
            'Area of the admin API this manager may access. Send these exact uppercase values in `managerPermissions` arrays. Admins bypass checks. `USERS` and `MANAGERS` gate the Users admin section (customer accounts vs manager accounts respectively) — neither ever grants access to ADMIN accounts or the ability to set anyone\'s role to ADMIN, even for a manager holding both.',
        },
        ManagerPermissionCatalogItem: {
          type: 'object',
          description: 'One selectable permission for the “create/edit manager” screen.',
          properties: {
            key: { $ref: '#/components/schemas/ManagerPermissionKey' },
            label: { type: 'string', example: 'Orders', description: 'Short label for UI' },
            description: {
              type: 'string',
              example: 'List all orders, view any order, update order status',
              description: 'What this permission allows (for tooltips or help text)',
            },
          },
        },
        ManagerPermissionCatalog: {
          type: 'object',
          properties: {
            permissions: {
              type: 'array',
              items: { $ref: '#/components/schemas/ManagerPermissionCatalogItem' },
              description: 'All keys the backend accepts; use to build checkboxes before POST/PATCH manager.',
            },
          },
        },
        User: {
          type: 'object',
          description:
            'Single user as returned by admin user APIs (`GET/POST/PUT /users`, `GET /users/{id}`). `role` and `status` are **title-cased** for display (e.g. `Manager`, `Active`). For managers, `managerPermissions` lists granted API areas; for others they are empty.',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Sam Lee', description: 'Display name (same as fullName)' },
            fullName: { type: 'string', nullable: true, example: 'Sam Lee', description: 'Canonical name field for the user' },
            email: { type: 'string', format: 'email' },
            avatar: {
              type: 'string',
              description: 'Image URL, or two-letter initials if no image is set',
              example: 'https://cdn.example.com/avatars/sam.jpg',
            },
            role: {
              type: 'string',
              enum: ['Customer', 'Admin', 'Manager'],
              description: 'Display form of DB role CUSTOMER / ADMIN / MANAGER',
            },
            managerTitle: {
              type: 'string',
              nullable: true,
              example: 'Operations lead',
              description: 'Job title; only for managers, otherwise null',
            },
            managerPermissions: {
              type: 'array',
              items: { $ref: '#/components/schemas/ManagerPermissionKey' },
              description: 'Granted keys; empty unless role is Manager',
            },
            status: { type: 'string', enum: ['Active', 'Inactive'], description: 'Display form of ACTIVE / INACTIVE' },
            isEmailVerified: { type: 'boolean' },
            regionId: { type: 'string', format: 'uuid', nullable: true, description: 'ID of the region this user belongs to (captured from X-Region at signup)' },
            region: {
              allOf: [{ $ref: '#/components/schemas/RegionRef' }],
              nullable: true,
              description: 'The user\'s region (null if unassigned)',
            },
            joinedAt: { type: 'string', format: 'date-time', description: 'Same as createdAt' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        UserInput: {
          type: 'object',
          required: ['email', 'fullName', 'password'],
          description:
            'Create user (admin). For **MANAGER**, also send `managerTitle` and non-empty `managerPermissions`. **ADMIN** cannot be created here (`403`).',
          properties: {
            email: { type: 'string', format: 'email' },
            fullName: { type: 'string', example: 'Sam Lee' },
            password: { type: 'string', format: 'password', description: 'Login password for the new account' },
            role: {
              type: 'string',
              enum: ['CUSTOMER', 'MANAGER'],
              default: 'CUSTOMER',
              description: 'Use MANAGER for staff with limited API access',
            },
            status: {
              type: 'string',
              enum: ['ACTIVE', 'INACTIVE'],
              default: 'ACTIVE',
              description: 'INACTIVE blocks login',
            },
            avatar: {
              type: 'string',
              nullable: true,
              description: 'Public image URL (upload via `POST /upload/image` first if needed)',
            },
            managerTitle: {
              type: 'string',
              description: '**Required** when `role` is `MANAGER` (e.g. “Inventory specialist”)',
            },
            managerPermissions: {
              type: 'array',
              items: { $ref: '#/components/schemas/ManagerPermissionKey' },
              minItems: 1,
              description: '**Required** when `role` is `MANAGER`; at least one key. Load options from `GET /users/manager-permissions`.',
            },
          },
        },
        UserUpdateInput: {
          type: 'object',
          description:
            'Partial update (admin). Send only fields to change. If the user is or becomes a **MANAGER**, `managerTitle` and at least one `managerPermissions` must remain valid (see server validation). Clearing role to CUSTOMER/ADMIN clears manager fields.',
          properties: {
            email: { type: 'string', format: 'email' },
            fullName: { type: 'string' },
            password: { type: 'string', format: 'password', description: 'New password; omit to keep current' },
            role: { type: 'string', enum: ['CUSTOMER', 'ADMIN', 'MANAGER'] },
            status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'] },
            avatar: { type: 'string', nullable: true },
            managerTitle: { type: 'string', description: 'Required for manager accounts' },
            managerPermissions: {
              type: 'array',
              items: { $ref: '#/components/schemas/ManagerPermissionKey' },
              minItems: 1,
              description: 'Replace entire permission set when sent',
            },
          },
        },
        UserStats: {
          type: 'object',
          description: 'Counts for admin dashboard (`GET /users/stats`).',
          properties: {
            total: { type: 'integer', example: 120, description: 'All users' },
            customers: { type: 'integer', example: 100 },
            admins: { type: 'integer', example: 1 },
            managers: { type: 'integer', example: 5, description: 'Users with role MANAGER' },
            active: { type: 'integer', example: 115, description: 'status ACTIVE' },
            inactive: { type: 'integer', example: 5, description: 'status INACTIVE' },
          },
        },
        ChangeUserRoleInput: {
          type: 'object',
          required: ['role'],
          description:
            'Change role (admin). When setting **MANAGER**, you must include `managerTitle` and `managerPermissions` (≥1). Other roles clear manager fields.',
          properties: {
            role: { type: 'string', enum: ['CUSTOMER', 'ADMIN', 'MANAGER'] },
            managerTitle: { type: 'string', description: 'Required if role is MANAGER' },
            managerPermissions: {
              type: 'array',
              items: { $ref: '#/components/schemas/ManagerPermissionKey' },
              minItems: 1,
              description: 'Required if role is MANAGER',
            },
          },
        },
        AuthUser: {
          type: 'object',
          description:
            'User object inside auth responses (signup/signin). For **MANAGER**, includes managerTitle and managerPermissions (same keys as GET /users/manager-permissions). Other roles use null and [].',
          properties: {
            id: {
              type: 'string',
              format: 'uuid',
              description: 'User UUID',
            },
            email: {
              type: 'string',
              format: 'email',
            },
            fullName: {
              type: 'string',
              nullable: true,
              description: 'Canonical display name',
            },
            role: { type: 'string', enum: ['CUSTOMER', 'ADMIN', 'MANAGER'], description: 'Raw DB enum (not title-cased)' },
            status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'] },
            regionId: { type: 'string', format: 'uuid', nullable: true, description: 'Region assigned at signup (from X-Region header)' },
            managerTitle: { type: 'string', nullable: true },
            managerPermissions: {
              type: 'array',
              items: { $ref: '#/components/schemas/ManagerPermissionKey' },
              description: 'Populated when role is MANAGER',
            },
            isEmailVerified: {
              type: 'boolean',
            },
            createdAt: {
              type: 'string',
              format: 'date-time',
            },
            updatedAt: {
              type: 'string',
              format: 'date-time',
            },
          },
        },
        UserProfile: {
          type: 'object',
          description: 'Current user profile (token-based). Includes phone, preferred language and address.',
          properties: {
            id: { type: 'string', format: 'uuid', description: 'User UUID' },
            email: { type: 'string', format: 'email', description: 'User email' },
            fullName: { type: 'string', nullable: true, description: 'Canonical display name' },
            avatar: { type: 'string', nullable: true, description: 'Profile image URL' },
            role: { type: 'string', enum: ['CUSTOMER', 'ADMIN', 'MANAGER'], description: 'User role' },
            managerTitle: { type: 'string', nullable: true, description: 'Job title when role is MANAGER' },
            managerPermissions: {
              type: 'array',
              items: { type: 'string' },
              description: 'Permission keys when role is MANAGER; empty for other roles',
            },
            status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'], description: 'Account status' },
            isEmailVerified: { type: 'boolean', description: 'Email verification status' },
            phone: { type: 'string', nullable: true, example: '+971501234567', description: 'User phone number' },
            preferredLanguage: { type: 'string', nullable: true, example: 'en', description: 'User preferred language code (e.g. en, ar)' },
            regionId: { type: 'string', format: 'uuid', nullable: true, description: 'ID of the region this user belongs to' },
            region: {
              allOf: [{ $ref: '#/components/schemas/RegionRef' }],
              nullable: true,
              description: 'The user\'s region (null if unassigned)',
            },
            addressCountry: { type: 'string', nullable: true, example: 'United Arab Emirates', description: 'User address country (legacy field)' },
            addressCity: { type: 'string', nullable: true, example: 'Dubai', description: 'User address city (legacy field)' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        PreferredLanguageInput: {
          type: 'object',
          required: ['preferredLanguage'],
          properties: {
            preferredLanguage: {
              type: 'string',
              example: 'en',
              description: 'Preferred language code (e.g. en, ar, fr). Stored for the authenticated user.',
            },
          },
        },
        AddressInput: {
          type: 'object',
          description:
            'Saved shipping address. **All fields are optional.** Recipient `fullName` and `phone` are read from the user profile at checkout time, so the address-add form does not need to collect them. `city` and `country` are typically pre-filled from the user profile (`addressCity`, `addressCountry`) on the client; the user can edit them before saving.',
          properties: {
            label: { type: 'string', nullable: true, example: 'Home', description: 'Friendly label (Home, Work, etc.)' },
            fullName: { type: 'string', nullable: true, example: 'Ahmed Al Mansouri', description: 'Optional. Recipient name. Usually omitted — server uses the user profile name on orders.' },
            phone: { type: 'string', nullable: true, example: '+971501234567', description: 'Optional. Recipient phone. Usually omitted — server uses the user profile phone on orders.' },
            streetAddress: { type: 'string', nullable: true, example: 'Villa 14, Al Wasl Road', description: 'Street / building address (line 1)' },
            apartment: { type: 'string', nullable: true, example: 'Apt 401', description: 'Apartment, floor, villa number (line 2)' },
            city: { type: 'string', nullable: true, example: 'Dubai', description: 'City. Pre-fill from user profile `addressCity` on the client.' },
            state: { type: 'string', nullable: true, example: 'Dubai', description: 'Emirate / state / province (legacy free text)' },
            postalCode: { type: 'string', nullable: true, example: null, description: 'Postal / ZIP code' },
            country: { type: 'string', nullable: true, example: 'United Arab Emirates', description: 'Country. Pre-fill from user profile `addressCountry` on the client.' },
            area: { type: 'string', nullable: true, example: 'Al Barsha', description: 'Neighborhood/community free text — the checkout form\'s primary location field.' },
            deliveryZoneId: { type: 'string', format: 'uuid', nullable: true, description: 'Selected zone (e.g. emirate) from GET /delivery-zones.' },
            isDefault: { type: 'boolean', example: true, description: 'Set as the default address for this user' },
          },
        },
        SavedAddress: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            label: { type: 'string', nullable: true, example: 'Home' },
            fullName: { type: 'string', nullable: true, example: null, description: 'Usually null on new addresses — name lives on the user profile.' },
            phone: { type: 'string', nullable: true, example: null, description: 'Usually null on new addresses — phone lives on the user profile.' },
            streetAddress: { type: 'string', nullable: true, example: 'Villa 14, Al Wasl Road' },
            apartment: { type: 'string', nullable: true, example: null },
            city: { type: 'string', nullable: true, example: 'Dubai' },
            state: { type: 'string', nullable: true, example: 'Dubai' },
            postalCode: { type: 'string', nullable: true, example: null },
            country: { type: 'string', nullable: true, example: 'United Arab Emirates' },
            isDefault: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        PushTokenRegister: {
          type: 'object',
          required: ['fcmToken'],
          properties: {
            fcmToken: {
              type: 'string',
              description: 'FCM registration token from the mobile SDK',
              example: 'dK3x...long-token...',
            },
            platform: {
              type: 'string',
              enum: ['IOS', 'ANDROID', 'WEB'],
              default: 'ANDROID',
              description: 'Client platform (case-insensitive in API)',
            },
          },
        },
        PushTokenUnregister: {
          type: 'object',
          required: ['fcmToken'],
          properties: {
            fcmToken: { type: 'string', description: 'Same token previously registered' },
          },
        },
        NotificationPreferences: {
          type: 'object',
          description: 'All default **true** when the row is first created.',
          properties: {
            orderStatus: {
              type: 'boolean',
              example: true,
              description: 'Order placed, confirmed, processing, shipped, delivered, cancelled',
            },
            promotions: {
              type: 'boolean',
              example: true,
              description: 'Marketing and offers (reserved for future campaigns)',
            },
            announcements: {
              type: 'boolean',
              example: true,
              description: 'App and store announcements (reserved for future use)',
            },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        NotificationPreferencesPatch: {
          type: 'object',
          description: 'Send at least one field; omitted fields stay unchanged.',
          properties: {
            orderStatus: { type: 'boolean' },
            promotions: { type: 'boolean' },
            announcements: { type: 'boolean' },
          },
        },
        SignupInput: {
          type: 'object',
          required: ['fullName', 'email', 'password'],
          properties: {
            fullName: {
              type: 'string',
              example: 'John Doe',
            },
            email: {
              type: 'string',
              format: 'email',
              example: 'john@example.com',
            },
            password: {
              type: 'string',
              example: 'password123',
            },
          },
        },
        SigninInput: {
          type: 'object',
          required: ['email', 'password'],
          properties: {
            email: {
              type: 'string',
              format: 'email',
              example: 'john@example.com',
            },
            password: {
              type: 'string',
              example: 'password123',
            },
          },
        },
        Error: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string', description: 'Error message' },
            errors: {
              type: 'array',
              items: { type: 'object', properties: { field: { type: 'string' }, message: { type: 'string' } } },
              description: 'Validation errors when present',
            },
          },
        },
        Review: {
          type: 'object',
          description: 'A customer star rating + written review for a product',
          properties: {
            id: { type: 'string', format: 'uuid' },
            productId: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid', nullable: true },
            rating: { type: 'integer', minimum: 1, maximum: 5, example: 5 },
            comment: { type: 'string', example: 'Beautifully arranged, loved it!' },
            reviewerName: { type: 'string', example: 'Sara Ahmed' },
            reviewerAvatar: { type: 'string', nullable: true },
            isGuest: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Category: {
          type: 'object',
          description: 'Product category',
          properties: {
            id: { type: 'string', format: 'uuid', example: '550e8400-e29b-41d4-a716-446655440000' },
            title: { type: 'string', example: 'Women' },
            title_ar: { type: 'string', nullable: true, example: 'نساء', description: 'Arabic category name (optional)' },
            description: { type: 'string', example: 'Women collection' },
            description_ar: { type: 'string', nullable: true, example: 'مجموعة نسائية', description: 'Arabic description (optional)' },
            image: { type: 'string', nullable: true },
            totalProducts: { type: 'integer', example: 5 },
            status: { $ref: '#/components/schemas/PublishStatus' },
            regions: {
              type: 'array',
              items: { $ref: '#/components/schemas/RegionRef' },
              description: 'Regions this category is visible in. Only present on staff/admin reads (storefront responses omit it).',
            },
            regionIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'IDs of the regions this category is visible in. Staff/admin reads only.',
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CategoryCreate: {
          type: 'object',
          required: ['title'],
          properties: {
            title: { type: 'string', example: 'Women', description: 'Category name' },
            title_ar: { type: 'string', nullable: true, example: 'نساء', description: 'Arabic category name (optional)' },
            description: { type: 'string', example: 'Women collection' },
            description_ar: { type: 'string', nullable: true, example: 'مجموعة نسائية', description: 'Arabic description (optional)' },
            image: { type: 'string', nullable: true },
            status: {
              allOf: [{ $ref: '#/components/schemas/PublishStatus' }],
              description: 'Publish state. Omitted → defaults to DRAFT (hidden from storefront until published).',
            },
            regionIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'Regions this category is visible in (IDs from GET /regions). Omitted → defaults to the default region only.',
              example: [],
            },
          },
        },
        Product: {
          type: 'object',
          description: 'Product with price, category, ordered images, and multiple descriptions (title optional per item)',
          properties: {
            id: { type: 'string', format: 'uuid' },
            title: { type: 'string', example: 'Summer Dress' },
            title_ar: { type: 'string', nullable: true, example: 'فستان صيفي', description: 'Arabic product name (optional)' },
            subtitle: { type: 'string', nullable: true },
            subtitle_ar: { type: 'string', nullable: true, example: 'قطن خفيف', description: 'Arabic subtitle (optional)' },
            image: { type: 'string', nullable: true, description: 'First image URL (thumbnail)' },
            images: { type: 'array', items: { type: 'string' }, description: 'All image URLs in display order (first = top)' },
            descriptions: {
              type: 'array',
              description: 'Multiple description blocks. Each has optional title and required description. If only one, title can be omitted.',
              items: {
                type: 'object',
                properties: {
                  id: { type: 'string', format: 'uuid' },
                  title: { type: 'string', nullable: true, description: 'Optional section title (e.g. "Materials")' },
                  title_ar: { type: 'string', nullable: true, description: 'Arabic section title (optional)' },
                  description: { type: 'string', description: 'Description text' },
                  description_ar: { type: 'string', nullable: true, description: 'Arabic description text (optional)' },
                },
              },
            },
            productOptions: {
              type: 'array',
              description: 'Optional custom options per product (e.g. Box Color: red, blue, black; Flower Color: orange, red, blue). Each item has title and options array. Use options_ar for Arabic option labels (parallel array, 1:1 with options).',
              items: {
                type: 'object',
                properties: {
                  id: { type: 'string', format: 'uuid' },
                  title: { type: 'string', example: 'Box Color' },
                  title_ar: { type: 'string', nullable: true, example: 'لون الصندوق', description: 'Arabic option group title (optional)' },
                  options: { type: 'array', items: { type: 'string' }, example: ['red', 'blue', 'black'] },
                  options_ar: { type: 'array', items: { type: 'string' }, example: ['أحمر', 'أزرق', 'أسود'], description: 'Arabic labels for each option, same order as options (optional)' },
                },
              },
            },
            price: { type: 'number', format: 'float', example: 49.99 },
            discountedPrice: { type: 'number', format: 'float', nullable: true, example: 39.99 },
            quantity: { type: 'integer', example: 10, description: 'Stock quantity (admin tracking)' },
            categoryId: { type: 'string', format: 'uuid', nullable: true },
            category: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string' } } },
            status: { $ref: '#/components/schemas/PublishStatus' },
            regions: {
              type: 'array',
              items: { $ref: '#/components/schemas/RegionRef' },
              description: 'Regions this product is visible in. Only present on staff/admin reads (storefront responses omit it).',
            },
            regionIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'IDs of the regions this product is visible in. Staff/admin reads only.',
            },
            regionPrices: {
              type: 'array',
              description: 'Per-region manual price overrides (no auto FX conversion). One entry per visible region; null price/discountedPrice means that region falls back to the base price above. Staff/admin reads only.',
              items: {
                type: 'object',
                properties: {
                  regionId: { type: 'string', format: 'uuid' },
                  price: { type: 'number', format: 'float', nullable: true, example: 189.0 },
                  discountedPrice: { type: 'number', format: 'float', nullable: true, example: 149.0 },
                },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ProductCreate: {
          type: 'object',
          required: ['title', 'price'],
          properties: {
            title: { type: 'string', example: 'Summer Dress' },
            title_ar: { type: 'string', nullable: true, example: 'فستان صيفي', description: 'Arabic product name (optional)' },
            subtitle: { type: 'string', example: 'Light cotton' },
            subtitle_ar: { type: 'string', nullable: true, example: 'قطن خفيف', description: 'Arabic subtitle (optional)' },
            descriptions: {
              type: 'array',
              description: 'Multiple descriptions. Each item: title (optional), description (required). Single description needs no title.',
              items: {
                type: 'object',
                required: ['description'],
                properties: {
                  title: { type: 'string', nullable: true, example: 'Materials' },
                  title_ar: { type: 'string', nullable: true, example: 'المواد', description: 'Arabic section title (optional)' },
                  description: { type: 'string', example: '100% cotton' },
                  description_ar: { type: 'string', nullable: true, example: '١٠٠٪ قطن', description: 'Arabic description (optional)' },
                },
              },
            },
            price: { type: 'number', example: 49.99 },
            discountedPrice: { type: 'number', nullable: true, example: 39.99 },
            giftCardEnabled: { type: 'boolean', example: true, description: 'Offer a free gift-card message add-on at add-to-cart time.' },
            giftCardExtraPrice: { type: 'number', nullable: true, example: 0, description: 'Extra charge for the gift card add-on (usually 0/free).' },
            customNameEnabled: { type: 'boolean', example: false, description: 'Offer a paid "add a custom name" add-on at add-to-cart time.' },
            customNamePrice: { type: 'number', nullable: true, example: 10, description: 'Extra charge when the custom name add-on is selected.' },
            quantity: { type: 'integer', minimum: 0, example: 10, description: 'Stock quantity for admin tracking' },
            categoryId: {
              type: 'string',
              format: 'uuid',
              nullable: true,
              example: '550e8400-e29b-41d4-a716-446655440000',
              description:
                'Optional. UUID of the category this product belongs to. List categories with **GET /categories** (each item has `id`); paste that `id` here. Omit to create uncategorized; change later with **PUT /products/{id}** and `categoryId`. Invalid id → **404**.',
            },
            images: {
              type: 'array',
              maxItems: 10,
              items: { type: 'string', format: 'uri', description: 'Public image URL (e.g. from POST /upload/image)' },
              description:
                'Optional. Up to 10 image URLs in display order (first = primary / thumbnail). Upload files via POST /upload/image?path=products, then use the returned urls here.',
              example: ['https://cdn.example.com/products/1.jpg', 'https://cdn.example.com/products/2.jpg'],
            },
            productOptions: {
              type: 'array',
              description: 'Optional. Multiple title + options. Use options_ar for Arabic option labels (parallel array, same order as options).',
              items: {
                type: 'object',
                required: ['title'],
                properties: {
                  title: { type: 'string', example: 'Box Color' },
                  title_ar: { type: 'string', nullable: true, example: 'لون الصندوق', description: 'Arabic option group title (optional)' },
                  options: { type: 'array', items: { type: 'string' }, example: ['red', 'blue', 'black'] },
                  options_ar: { type: 'array', items: { type: 'string' }, example: ['أحمر', 'أزرق', 'أسود'], description: 'Arabic labels for options (optional, 1:1 with options)' },
                },
              },
            },
            status: {
              allOf: [{ $ref: '#/components/schemas/PublishStatus' }],
              description: 'Publish state. Omitted → defaults to DRAFT (hidden from storefront until published).',
            },
            regionIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'Regions this product is visible in (IDs from GET /regions). Both regions = list both; one = single-region. Omitted → defaults to the default region only.',
              example: [],
            },
            regionPrices: {
              type: 'array',
              description: 'Optional per-region manual price overrides (no auto FX conversion — enter each region’s price explicitly). One entry per region that needs an override; a region left out (or with null price/discountedPrice) falls back to the base price above.',
              items: {
                type: 'object',
                required: ['regionId'],
                properties: {
                  regionId: { type: 'string', format: 'uuid', description: 'Region id from GET /regions.' },
                  price: { type: 'number', nullable: true, example: 189.0, description: 'Region-specific price. Omit/null to use the base price above.' },
                  discountedPrice: { type: 'number', nullable: true, example: 149.0, description: 'Region-specific discounted price. Must not exceed this entry’s price.' },
                },
              },
              example: [],
            },
          },
        },
        ProductUpdate: {
          type: 'object',
          description: [
            'Admin partial update: include **only** fields you want to change; omitted fields stay as-is.',
            'Updatable fields match create: **title**, **subtitle**, **price**, **discountedPrice**, **quantity** (stock), **categoryId**, **descriptions**, **images**, **productOptions**.',
            '**Replace semantics:** sending **descriptions**, **images**, or **productOptions** replaces that entire list (use empty array `[]` to clear images or descriptions; options cleared similarly).',
            'New image files: **POST /upload/image** (e.g. `?path=products`), then put returned URLs in **images**.',
          ].join(' '),
          example: {
            title: 'Summer Dress — sale',
            subtitle: 'Light organic cotton',
            price: 44.99,
            discountedPrice: 34.99,
            quantity: 25,
            categoryId: '550e8400-e29b-41d4-a716-446655440000',
            descriptions: [
              { title: 'Care', description: 'Machine wash cold' },
              { description: 'Relaxed fit' },
            ],
            images: [
              'https://cdn.example.com/products/dress-front-v2.jpg',
              'https://cdn.example.com/products/dress-detail.jpg',
            ],
            productOptions: [
              { title: 'Size', options: ['S', 'M', 'L', 'XL'] },
              { title: 'Color', options: ['Ivory', 'Sage'] },
            ],
          },
          properties: {
            title: { type: 'string', example: 'Summer Dress — updated', description: 'Product name' },
            title_ar: { type: 'string', nullable: true, example: 'فستان صيفي', description: 'Arabic product name (optional)' },
            subtitle: {
              type: 'string',
              nullable: true,
              example: 'Light organic cotton',
              description: 'Short tagline; send `null` or empty to clear if your client supports it',
            },
            subtitle_ar: { type: 'string', nullable: true, example: 'قطن عضوي خفيف', description: 'Arabic subtitle (optional)' },
            descriptions: {
              type: 'array',
              description:
                'When present, **replaces** all descriptions. Same items as POST /products (`description` required per row; `title` optional).',
              items: {
                type: 'object',
                required: ['description'],
                properties: {
                  title: { type: 'string', nullable: true, example: 'Materials' },
                  title_ar: { type: 'string', nullable: true, example: 'المواد', description: 'Arabic section title (optional)' },
                  description: { type: 'string', example: '100% cotton' },
                  description_ar: { type: 'string', nullable: true, example: '١٠٠٪ قطن', description: 'Arabic description (optional)' },
                },
              },
              example: [{ title: 'Care', description: 'Machine wash cold' }, { description: 'Relaxed fit' }],
            },
            price: { type: 'number', format: 'float', example: 49.99, description: 'Regular price' },
            discountedPrice: {
              type: 'number',
              format: 'float',
              nullable: true,
              example: 39.99,
              description: 'Sale price; omit to leave unchanged, or set as needed',
            },
            quantity: {
              type: 'integer',
              minimum: 0,
              example: 25,
              description: 'Stock / inventory count (admin). Non-negative integer.',
            },
            categoryId: {
              type: 'string',
              format: 'uuid',
              nullable: true,
              example: '550e8400-e29b-41d4-a716-446655440000',
              description:
                'Set or move to another category using the category\'s `id` from **GET /categories**. Send `null` to remove the product from any category.',
            },
            images: {
              type: 'array',
              maxItems: 10,
              items: { type: 'string', format: 'uri', description: 'Public image URL (e.g. from POST /upload/image)' },
              description:
                'When present, **replaces** the full gallery (order = array order, first = thumbnail). Up to 10 URLs. `[]` removes all images.',
              example: ['https://cdn.example.com/products/1.jpg', 'https://cdn.example.com/products/2.jpg'],
            },
            productOptions: {
              type: 'array',
              description: 'When present, **replaces** all variant-style options (same shape as create). Use options_ar for Arabic labels.',
              items: {
                type: 'object',
                required: ['title'],
                properties: {
                  title: { type: 'string', example: 'Size' },
                  title_ar: { type: 'string', nullable: true, example: 'المقاس', description: 'Arabic option group title (optional)' },
                  options: { type: 'array', items: { type: 'string' }, example: ['S', 'M', 'L'] },
                  options_ar: { type: 'array', items: { type: 'string' }, example: ['صغير', 'وسط', 'كبير'], description: 'Arabic labels for options (optional, 1:1 with options)' },
                },
              },
              example: [{ title: 'Size', options: ['S', 'M', 'L'] }, { title: 'Color', options: ['Ivory', 'Sage'] }],
            },
            status: {
              allOf: [{ $ref: '#/components/schemas/PublishStatus' }],
              description: 'Set PUBLISHED to make the product live, or DRAFT to hide it from the storefront.',
            },
            regionIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'When present, **replaces** the product\'s region set (IDs from GET /regions).',
              example: [],
            },
          },
        },
        CartItem: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            productId: { type: 'string', format: 'uuid' },
            product: { $ref: '#/components/schemas/Product' },
            quantity: { type: 'integer', example: 2 },
            message: { type: 'string', nullable: true, description: 'Per-item note (e.g. gift wrap)' },
            lineTotal: { type: 'number', example: 79.98 },
          },
        },
        Cart: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            items: { type: 'array', items: { $ref: '#/components/schemas/CartItem' } },
            totalAmount: { type: 'number', example: 99.97 },
            orderMessage: { type: 'string', nullable: true, description: 'Optional note for the whole order' },
          },
        },
        CartAddBody: {
          type: 'object',
          required: ['productId'],
          properties: {
            productId: { type: 'string', format: 'uuid', example: '550e8400-e29b-41d4-a716-446655440000' },
            quantity: { type: 'integer', minimum: 1, example: 1 },
            message: { type: 'string', example: 'Gift wrap please' },
          },
        },
        Order: {
          type: 'object',
          description:
            '**Stock is reserved (deducted) at order placement** per line (**409** if insufficient), so a PENDING_PAYMENT order already holds its stock. **CANCELLED** restores stock whenever **inventoryDeducted** is true (incl. the auto-expiry of unpaid online orders). Reverting to **PENDING_PAYMENT** from processing/completed also restores. **ON_HOLD/REFUNDED/FAILED/DRAFT** are pure labels with no stock side effects. **inventoryDeducted** reflects whether deduction is active.',
          properties: {
            id: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            orderMessage: { type: 'string', nullable: true },
            totalAmount: { type: 'number', example: 99.97 },
            paymentMethod: {
              type: 'string',
              enum: ['COD', 'MYFATOORAH'],
              description: 'COD = cash on delivery. MYFATOORAH = pay online (Apple Pay / cards) via POST /orders/{id}/pay.',
            },
            paymentStatus: {
              type: 'string',
              enum: ['UNPAID', 'PAID', 'FAILED'],
              description: 'Online-payment state. COD stays UNPAID. MYFATOORAH flips to PAID once the payment is verified, FAILED if declined/cancelled.',
            },
            status: {
              type: 'string',
              enum: ['PENDING_PAYMENT', 'PROCESSING', 'ON_HOLD', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'FAILED', 'DRAFT'],
              description: 'PENDING_PAYMENT = order placed, payment not yet confirmed (a normal, visible order — both COD and unpaid online orders start here). On confirmation it becomes PROCESSING.',
            },
            inventoryDeducted: {
              type: 'boolean',
              description: 'True after a successful **PROCESSING** transition deducted catalog stock for this order',
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            items: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: { type: 'string' },
                  productId: { type: 'string' },
                  product: { type: 'object' },
                  quantity: { type: 'integer' },
                  perProductMessage: { type: 'string', nullable: true },
                  price: { type: 'number' },
                },
              },
            },
          },
        },
        OrderStatusUpdate: {
          type: 'object',
          required: ['status'],
          properties: {
            status: {
              type: 'string',
              enum: ['PENDING_PAYMENT', 'PROCESSING', 'ON_HOLD', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'FAILED', 'DRAFT'],
              example: 'PROCESSING',
            },
          },
        },
        OrderStatusSnapshot: {
          type: 'object',
          description: 'Lightweight order status from **GET /orders/{id}/status** (post-checkout polling).',
          properties: {
            id: { type: 'string', format: 'uuid' },
            status: {
              type: 'string',
              enum: ['PENDING_PAYMENT', 'PROCESSING', 'ON_HOLD', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'FAILED', 'DRAFT'],
            },
            paymentStatus: {
              type: 'string',
              enum: ['UNPAID', 'PAID', 'FAILED'],
              description: 'Poll this after an online payment to see when it becomes PAID.',
            },
            totalAmount: { type: 'number' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            progress: {
              type: 'object',
              properties: {
                currentStep: { type: 'string' },
                isTerminal: { type: 'boolean', description: 'True when COMPLETED, CANCELLED, REFUNDED, or FAILED' },
                typicalFlow: {
                  type: 'array',
                  items: { type: 'string' },
                  description: 'Common fulfillment sequence for UI steppers (PENDING_PAYMENT, PROCESSING, COMPLETED)',
                },
                stepIndex: { type: 'integer', nullable: true },
              },
            },
          },
        },
        CartSuggestions: {
          type: 'object',
          description:
            'Payload inside **data** for **GET /cart/suggestions**. Non-empty cart: **sections** by category + **discover** from other categories. Empty cart: **sections** is empty and **discover** is a random in-stock sample.',
          properties: {
            headline: { type: 'string', example: 'Complete your look' },
            hint: { type: 'string', description: 'UX copy; empty cart explains random picks vs category-based mode' },
            sections: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  category: {
                    type: 'object',
                    properties: {
                      id: { type: 'string', format: 'uuid' },
                      title: { type: 'string' },
                    },
                  },
                  headline: { type: 'string' },
                  subhead: { type: 'string' },
                  products: { type: 'array', items: { $ref: '#/components/schemas/Product' } },
                },
              },
            },
            discover: {
              type: 'array',
              items: { $ref: '#/components/schemas/Product' },
              description: 'In-stock picks from categories not represented in the cart',
            },
          },
        },
        RevenueAnalyticsSummary: {
          type: 'object',
          description: 'Totals for the selected window. **revenue** excludes CANCELLED and REFUNDED orders.',
          properties: {
            activeOrderCount: { type: 'integer', description: 'Orders with status other than CANCELLED/REFUNDED' },
            revenue: { type: 'number', description: 'Sum of totalAmount for non-cancelled, non-refunded orders' },
            averageOrderValue: { type: 'number' },
            cancelledOrderCount: { type: 'integer' },
            cancelledRevenue: { type: 'number', description: 'Sum of totalAmount for cancelled orders' },
            distinctCustomers: { type: 'integer', description: 'Unique userId among non-cancelled, non-refunded orders' },
          },
        },
        RevenueSeriesPoint: {
          type: 'object',
          description: 'One time bucket for line or bar charts',
          properties: {
            periodStart: { type: 'string', format: 'date-time' },
            orderCount: { type: 'integer' },
            revenue: { type: 'number' },
            cancelledOrderCount: { type: 'integer' },
            cancelledRevenue: { type: 'number' },
          },
        },
        OrderStatusBucket: {
          type: 'object',
          properties: {
            status: { type: 'string', enum: ['PENDING_PAYMENT', 'PROCESSING', 'ON_HOLD', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'FAILED', 'DRAFT'] },
            orderCount: { type: 'integer' },
            revenue: { type: 'number', description: 'Sum of totalAmount for this status in the window' },
          },
        },
        RevenueAnalyticsPayload: {
          type: 'object',
          properties: {
            preset: { type: 'string', nullable: true },
            presetLabel: { type: 'string' },
            currency: { type: 'string', example: 'USD', description: 'From site Settings' },
            range: {
              type: 'object',
              properties: {
                allTime: { type: 'boolean', description: 'True when preset is all_time' },
                from: { type: 'string', format: 'date-time', nullable: true },
                toExclusive: { type: 'string', format: 'date-time', nullable: true },
                timezoneNote: { type: 'string' },
              },
            },
            bucket: { type: 'string', enum: ['hour', 'day', 'week', 'month', 'quarter', 'year'], description: 'date_trunc unit for series (all_time uses month)' },
            summary: { $ref: '#/components/schemas/RevenueAnalyticsSummary' },
            series: { type: 'array', items: { $ref: '#/components/schemas/RevenueSeriesPoint' } },
            byStatus: { type: 'array', items: { $ref: '#/components/schemas/OrderStatusBucket' } },
          },
        },
        KpiStatusSlice: {
          type: 'object',
          properties: {
            orderCount: { type: 'integer' },
            revenue: { type: 'number' },
          },
        },
        KpiAnalyticsPayload: {
          type: 'object',
          description: 'Single-scan order aggregates plus units sold from line items (non-cancelled, non-refunded).',
          properties: {
            preset: { type: 'string', nullable: true },
            presetLabel: { type: 'string' },
            currency: { type: 'string' },
            range: { type: 'object' },
            totals: {
              type: 'object',
              properties: {
                totalOrdersAllStatuses: { type: 'integer' },
                grossRevenueAllStatuses: { type: 'number', description: 'Sum of order totals including cancelled/refunded' },
                netSalesCount: { type: 'integer', description: 'Orders excluding CANCELLED/REFUNDED' },
                netRevenue: { type: 'number', description: 'Revenue excluding cancelled and refunded orders' },
                averageOrderValue: { type: 'number', description: 'netRevenue / netSalesCount' },
                unitsSold: { type: 'integer', description: 'Sum of line quantities on non-cancelled, non-refunded orders' },
                distinctCustomers: { type: 'integer' },
              },
            },
            cancelled: {
              type: 'object',
              properties: {
                orderCount: { type: 'integer' },
                revenue: { type: 'number' },
              },
            },
            byStatus: {
              type: 'object',
              description: 'Fulfillment pipeline only; see **cancelled** for CANCELLED rows',
              properties: {
                PENDING_PAYMENT: { $ref: '#/components/schemas/KpiStatusSlice' },
                PROCESSING: { $ref: '#/components/schemas/KpiStatusSlice' },
                ON_HOLD: { $ref: '#/components/schemas/KpiStatusSlice' },
                COMPLETED: { $ref: '#/components/schemas/KpiStatusSlice' },
                REFUNDED: { $ref: '#/components/schemas/KpiStatusSlice' },
                FAILED: { $ref: '#/components/schemas/KpiStatusSlice' },
                DRAFT: { $ref: '#/components/schemas/KpiStatusSlice' },
              },
            },
          },
        },
        CategorySalesRow: {
          type: 'object',
          properties: {
            rank: { type: 'integer' },
            categoryId: { type: 'string', format: 'uuid', nullable: true },
            categoryTitle: { type: 'string' },
            orderCount: { type: 'integer', description: 'Distinct non-cancelled orders touching this category' },
            revenue: { type: 'number', description: 'Σ (quantity × line price)' },
            unitsSold: { type: 'integer' },
            lineItemCount: { type: 'integer' },
            revenueSharePercent: { type: 'number' },
          },
        },
        CategorySalesAnalyticsPayload: {
          type: 'object',
          properties: {
            preset: { type: 'string', nullable: true },
            presetLabel: { type: 'string' },
            currency: { type: 'string' },
            range: { type: 'object' },
            note: { type: 'string' },
            totalNetLineRevenue: { type: 'number' },
            categories: { type: 'array', items: { $ref: '#/components/schemas/CategorySalesRow' } },
          },
        },
        DailySalesDayPoint: {
          type: 'object',
          description: 'One UTC calendar day (or month when granularity is month)',
          properties: {
            date: { type: 'string', example: '2026-04-05', description: 'YYYY-MM-DD when granularity is day' },
            month: { type: 'string', example: '2026-04', description: 'YYYY-MM when granularity is month' },
            periodStart: { type: 'string', format: 'date-time', description: 'Bucket start (month mode)' },
            netOrderCount: { type: 'integer', description: 'Non-cancelled orders that day' },
            netRevenue: { type: 'number' },
            cancelledOrderCount: { type: 'integer' },
            cancelledRevenue: { type: 'number' },
          },
        },
        DailySalesSummary: {
          type: 'object',
          properties: {
            periodCount: { type: 'integer', description: 'Number of days (or months) in points' },
            netOrderCount: { type: 'integer' },
            netRevenue: { type: 'number' },
            averageNetRevenuePerPeriod: { type: 'number' },
            cancelledOrderCount: { type: 'integer' },
            cancelledRevenue: { type: 'number' },
            bestDay: {
              nullable: true,
              allOf: [{ $ref: '#/components/schemas/DailySalesDayPoint' }],
              description: 'Highest netRevenue day when granularity is day (omitted or null if flat)',
            },
            bestMonth: {
              nullable: true,
              allOf: [{ $ref: '#/components/schemas/DailySalesDayPoint' }],
              description: 'Highest netRevenue month when granularity is month',
            },
          },
        },
        DailySalesAnalyticsPayload: {
          type: 'object',
          properties: {
            preset: { type: 'string', nullable: true },
            presetLabel: { type: 'string' },
            currency: { type: 'string' },
            range: { type: 'object' },
            granularity: { type: 'string', enum: ['day', 'month'] },
            note: { type: 'string' },
            summary: { $ref: '#/components/schemas/DailySalesSummary' },
            points: { type: 'array', items: { $ref: '#/components/schemas/DailySalesDayPoint' } },
          },
        },
        ApiSuccess: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            message: { type: 'string' },
            data: { type: 'object' },
            meta: { type: 'object', description: 'Pagination or extra info' },
          },
        },
        BannerImage: {
          type: 'object',
          description: 'Landing page banner image (display order by sortOrder)',
          properties: {
            id: { type: 'string', format: 'uuid', description: 'Banner ID' },
            url: { type: 'string', description: 'Image URL (stored in DB; Bunny CDN can be used later)' },
            sortOrder: { type: 'integer', description: 'Display order (0 = first)' },
            status: { $ref: '#/components/schemas/PublishStatus' },
            regions: {
              type: 'array',
              items: { $ref: '#/components/schemas/RegionRef' },
              description: 'Regions this banner is shown in. Only present on staff/admin reads (storefront responses omit it).',
            },
            regionIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'IDs of the regions this banner is shown in. Staff/admin reads only.',
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        PromoCodeDiscountType: {
          type: 'string',
          enum: ['PERCENTAGE', 'FIXED'],
          description: 'PERCENTAGE — discountValue is 0–100. FIXED — discountValue is a flat amount in the store currency.',
        },
        PromoCodeAppliesTo: {
          type: 'string',
          enum: ['ALL_PRODUCTS', 'SPECIFIC_PRODUCTS', 'SPECIFIC_CATEGORIES'],
          description: 'Scope of the promo code: whole cart, specific products, or specific categories.',
        },
        PromoCodeRef: {
          type: 'object',
          description: 'Compact reference to a linked product or category on a promo code.',
          properties: {
            id: { type: 'string', format: 'uuid' },
            title: { type: 'string' },
          },
        },
        PromoCode: {
          type: 'object',
          description: 'A promo / discount code. Admin view includes usage counters.',
          properties: {
            id: { type: 'string', format: 'uuid' },
            code: { type: 'string', example: 'RAMADAN10', description: 'Uppercased unique code users type' },
            name: { type: 'string', example: 'Ramadan 10% off' },
            name_ar: { type: 'string', nullable: true, example: 'خصم رمضان ١٠٪', description: 'Arabic promo code name (optional)' },
            description: { type: 'string', nullable: true },
            description_ar: { type: 'string', nullable: true, example: 'عرض رمضان على المتجر بأكمله', description: 'Arabic description (optional)' },
            discountType: { $ref: '#/components/schemas/PromoCodeDiscountType' },
            discountValue: { type: 'number', example: 10 },
            maxDiscountAmount: {
              type: 'number',
              nullable: true,
              example: 50,
              description: 'Cap for PERCENTAGE discounts (optional).',
            },
            appliesTo: { $ref: '#/components/schemas/PromoCodeAppliesTo' },
            minOrderAmount: { type: 'number', nullable: true, example: 100 },
            maxOrderAmount: { type: 'number', nullable: true },
            startsAt: { type: 'string', format: 'date-time', nullable: true },
            expiresAt: { type: 'string', format: 'date-time', nullable: true },
            usageLimit: { type: 'integer', nullable: true, description: 'Total uses across all customers' },
            usageLimitPerUser: { type: 'integer', nullable: true, description: 'Per-customer cap' },
            usageCount: { type: 'integer', example: 7, description: 'Total successful redemptions so far' },
            newUsersOnly: { type: 'boolean', description: 'Only customers whose account is within newUserWithinDays days may redeem' },
            newUserWithinDays: { type: 'integer', nullable: true, description: 'Account-age window in days for newUsersOnly' },
            isActive: { type: 'boolean' },
            products: {
              type: 'array',
              items: { $ref: '#/components/schemas/PromoCodeRef' },
              description: 'Full list — present on detail / create / update responses (not on list).',
            },
            categories: {
              type: 'array',
              items: { $ref: '#/components/schemas/PromoCodeRef' },
              description: 'Full list — present on detail / create / update responses (not on list).',
            },
            productCount: {
              type: 'integer',
              description: 'Count of linked products. Present on LIST responses instead of the full `products` array.',
            },
            categoryCount: {
              type: 'integer',
              description: 'Count of linked categories. Present on LIST responses instead of the full `categories` array.',
            },
            totalUses: {
              type: 'integer',
              description: 'Denormalized usage count from `PromoCodeUsage` (matches `usageCount`).',
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        PromoCodeCreate: {
          type: 'object',
          required: ['code', 'name', 'discountType', 'discountValue'],
          description: [
            'Create a promo / discount code.',
            '',
            '**Scope:** Default is `ALL_PRODUCTS`. For `SPECIFIC_PRODUCTS`, also send `productIds` (UUIDs from **GET /products**). For `SPECIFIC_CATEGORIES`, send `categoryIds` (UUIDs from **GET /categories**).',
            '',
            '**Rules:** Combine `minOrderAmount` / `maxOrderAmount` for price-range promos, `startsAt` / `expiresAt` for availability, `usageLimit` for total caps, and `usageLimitPerUser` for per-customer caps.',
          ].join('\n'),
          properties: {
            code: {
              type: 'string',
              example: 'RAMADAN10',
              minLength: 2,
              maxLength: 40,
              description: 'Unique code. Stored uppercased; the server matches case-insensitively on validate.',
            },
            name: { type: 'string', example: 'Ramadan 10% off', description: 'Admin-facing display name' },
            name_ar: { type: 'string', nullable: true, example: 'خصم رمضان ١٠٪', description: 'Arabic promo code name (optional)' },
            description: { type: 'string', nullable: true, example: 'Store-wide Ramadan promotion' },
            description_ar: { type: 'string', nullable: true, example: 'عرض رمضان على المتجر بأكمله', description: 'Arabic description (optional)' },
            discountType: { $ref: '#/components/schemas/PromoCodeDiscountType' },
            discountValue: {
              type: 'number',
              example: 10,
              description: 'Percentage (0–100) for PERCENTAGE, or flat amount for FIXED',
            },
            maxDiscountAmount: {
              type: 'number',
              nullable: true,
              example: 50,
              description: 'Optional cap applied to PERCENTAGE discounts',
            },
            appliesTo: {
              allOf: [{ $ref: '#/components/schemas/PromoCodeAppliesTo' }],
              description: 'Defaults to ALL_PRODUCTS',
            },
            productIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'Required when appliesTo = SPECIFIC_PRODUCTS',
            },
            categoryIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'Required when appliesTo = SPECIFIC_CATEGORIES',
            },
            minOrderAmount: { type: 'number', nullable: true, example: 100 },
            maxOrderAmount: { type: 'number', nullable: true },
            startsAt: {
              type: 'string',
              format: 'date-time',
              nullable: true,
              example: '2026-03-10T00:00:00Z',
            },
            expiresAt: {
              type: 'string',
              format: 'date-time',
              nullable: true,
              example: '2026-04-10T00:00:00Z',
            },
            usageLimit: { type: 'integer', minimum: 1, nullable: true, example: 500 },
            usageLimitPerUser: { type: 'integer', minimum: 1, nullable: true, example: 1 },
            newUsersOnly: { type: 'boolean', default: false, example: true, description: 'Restrict to new customers (account age based)' },
            newUserWithinDays: { type: 'integer', minimum: 1, nullable: true, example: 7, description: 'Required when newUsersOnly: account must be at most this many days old' },
            isActive: { type: 'boolean', default: true },
          },
        },
        PromoCodeUpdate: {
          type: 'object',
          description: [
            'Partial update. Send only fields to change.',
            '',
            'Sending `productIds` or `categoryIds` **replaces** that list entirely. Changing `appliesTo` to a different scope clears the links from the previous scope.',
          ].join('\n'),
          properties: {
            code: { type: 'string', minLength: 2, maxLength: 40 },
            name: { type: 'string' },
            name_ar: { type: 'string', nullable: true, example: 'خصم رمضان ١٠٪', description: 'Arabic promo code name (optional)' },
            description: { type: 'string', nullable: true },
            description_ar: { type: 'string', nullable: true, example: 'عرض رمضان على المتجر بأكمله', description: 'Arabic description (optional)' },
            discountType: { $ref: '#/components/schemas/PromoCodeDiscountType' },
            discountValue: { type: 'number' },
            maxDiscountAmount: { type: 'number', nullable: true },
            appliesTo: { $ref: '#/components/schemas/PromoCodeAppliesTo' },
            productIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
            },
            categoryIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
            },
            minOrderAmount: { type: 'number', nullable: true },
            maxOrderAmount: { type: 'number', nullable: true },
            startsAt: { type: 'string', format: 'date-time', nullable: true },
            expiresAt: { type: 'string', format: 'date-time', nullable: true },
            usageLimit: { type: 'integer', minimum: 1, nullable: true },
            usageLimitPerUser: { type: 'integer', minimum: 1, nullable: true },
            newUsersOnly: { type: 'boolean' },
            newUserWithinDays: { type: 'integer', minimum: 1, nullable: true },
            isActive: { type: 'boolean' },
          },
        },
        PromoCodeValidateInput: {
          type: 'object',
          required: ['code'],
          properties: {
            code: { type: 'string', example: 'RAMADAN10' },
            items: {
              type: 'array',
              description:
                'Optional preview list. If omitted, the server uses the user\'s saved cart.',
              items: {
                type: 'object',
                required: ['productId', 'quantity'],
                properties: {
                  productId: { type: 'string', format: 'uuid' },
                  quantity: { type: 'integer', minimum: 1 },
                  price: {
                    type: 'number',
                    minimum: 0,
                    description: 'Optional; defaults to product.discountedPrice ?? product.price',
                  },
                  categoryId: {
                    type: 'string',
                    format: 'uuid',
                    nullable: true,
                    description: 'Optional; auto-hydrated from the product if missing',
                  },
                },
              },
            },
          },
        },
        PromoCodeValidateResult: {
          type: 'object',
          description: 'Returned from `POST /promo-codes/validate` when the code is usable.',
          properties: {
            promoCode: {
              type: 'object',
              properties: {
                id: { type: 'string', format: 'uuid' },
                code: { type: 'string' },
                name: { type: 'string' },
                name_ar: { type: 'string', nullable: true, description: 'Arabic promo code name (optional)' },
                discountType: { $ref: '#/components/schemas/PromoCodeDiscountType' },
                discountValue: { type: 'number' },
                appliesTo: { $ref: '#/components/schemas/PromoCodeAppliesTo' },
              },
            },
            cartSubtotal: { type: 'number', example: 600 },
            eligibleSubtotal: {
              type: 'number',
              example: 600,
              description: 'Subtotal of items the code applies to (= cartSubtotal for ALL_PRODUCTS)',
            },
            discountAmount: { type: 'number', example: 60 },
            total: { type: 'number', example: 540, description: 'cartSubtotal − discountAmount' },
            eligibleProductIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'Product IDs from the cart that the discount applied to',
            },
          },
        },
        SectionWithItems: {
          type: 'object',
          description: 'Section with products and categories (same shape as product list and category list)',
          properties: {
            id: { type: 'string', format: 'uuid' },
            title: { type: 'string', example: 'Ramadan Deals' },
            title_ar: { type: 'string', nullable: true, example: 'عروض رمضان', description: 'Arabic section title (optional)' },
            image: { type: 'string', nullable: true },
            sortOrder: { type: 'integer' },
            status: { $ref: '#/components/schemas/PublishStatus' },
            regions: {
              type: 'array',
              items: { $ref: '#/components/schemas/RegionRef' },
              description: 'Regions this section is shown in. Only present on staff/admin reads. For storefront requests, the nested products/categories are themselves region+published filtered.',
            },
            regionIds: {
              type: 'array',
              items: { type: 'string', format: 'uuid' },
              description: 'IDs of the regions this section is shown in. Staff/admin reads only.',
            },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            products: {
              type: 'array',
              items: { $ref: '#/components/schemas/Product' },
              description: 'Products in section (id, image, title, price, etc. as in product API)',
            },
            categories: {
              type: 'array',
              items: { $ref: '#/components/schemas/Category' },
              description: 'Categories in section (id, title, image, totalProducts, etc.)',
            },
          },
        },
      },
    },
  },
  apis: [
    './src/routes/auth.routes.js',
    './src/routes/user.routes.js',
    './src/routes/userProfile.routes.js',
    './src/routes/upload.routes.js',
    './src/routes/category.routes.js',
    './src/routes/product.routes.js',
    './src/routes/cart.routes.js',
    './src/routes/order.routes.js',
    './src/routes/banner.routes.js',
    './src/routes/section.routes.js',
    './src/routes/region.routes.js',
    './src/routes/deliveryZone.routes.js',
    './src/routes/analytics.routes.js',
    './src/routes/promoCode.routes.js',
    './src/routes/address.routes.js',
    './src/routes/contact.routes.js',
    './src/routes/review.routes.js',
  ],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
